import { Inter } from 'next/font/google'
import './globals.css'
import style from '../style/root.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <section className={style.landing}>{children}</section>
      </body>
    </html>
  )
}
